/// <reference path="../pb_data/types.d.ts" />
migrate((db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("6n2w0ntksia5pn2")

  // update
  collection.schema.addField(new SchemaField({
    "system": false,
    "id": "lzlwrb1t",
    "name": "topics",
    "type": "select",
    "required": true,
    "presentable": false,
    "unique": false,
    "options": {
      "maxSelect": 3,
      "values": [
        "Android",
        "Android Architecture",
        "Android Compose",
        "Android Jetpack",
        "Android Testing",
        "Flutter",
        "Flutter Architecture",
        "Flutter Testing",
        "Flutter Web",
        "Flutter Desktop",
        "State Management",
        "Animation",
        "UI/UX Design",
        "Mobile Security",
        "Cross-Platform Development",
        "Kotlin",
        "Dart",
        "Cloud",
        "Firebase",
        "Google Cloud Platform",
        "Cloud Functions",
        "Cloud Storage",
        "App Engine",
        "Cloud Run",
        "Kubernetes",
        "DevOps",
        "Serverless",
        "Database",
        "API Development",
        "AI",
        "Machine Learning",
        "TensorFlow",
        "TensorFlow js",
        "TensorFlow Lite",
        "Gemini",
        "Gemma",
        "MLKit",
        "Computer Vision",
        "Natural Language Processing",
        "AI Ethics",
        "Generative AI",
        "Web",
        "Progressive Web Apps",
        "Web Performance",
        "Web Security",
        "Angular",
        "Material Design",
        "DevFest",
        "Google I/O Extended",
        "Community Building",
        "Diversity in Tech",
        "Women in Tech",
        "Tech Leadership",
        "Career Development",
        "Open Source",
        "Code Labs",
        "Hackathon",
        "Business",
        "Entrepreneurship",
        "Startup Development",
        "Product Management",
        "Technical Writing",
        "Developer Relations",
        "Google Play",
        "App Monetization",
        "Project Management",
        "AR/VR",
        "Internet of Things",
        "Edge Computing",
        "Blockchain",
        "5G Technologies",
        "Quantum Computing"
      ]
    }
  }))

  return dao.saveCollection(collection)
}, (db) => {
  const dao = new Dao(db)
  const collection = dao.findCollectionByNameOrId("6n2w0ntksia5pn2")

  // update
  collection.schema.addField(new SchemaField({
    "system": false,
    "id": "lzlwrb1t",
    "name": "topics",
    "type": "select",
    "required": false,
    "presentable": false,
    "unique": false,
    "options": {
      "maxSelect": 3,
      "values": [
        "Android",
        "Android Architecture",
        "Android Compose",
        "Android Jetpack",
        "Android Testing",
        "Flutter",
        "Flutter Architecture",
        "Flutter Testing",
        "Flutter Web",
        "Flutter Desktop",
        "State Management",
        "Animation",
        "UI/UX Design",
        "Mobile Security",
        "Cross-Platform Development",
        "Kotlin",
        "Dart",
        "Cloud",
        "Firebase",
        "Google Cloud Platform",
        "Cloud Functions",
        "Cloud Storage",
        "App Engine",
        "Cloud Run",
        "Kubernetes",
        "DevOps",
        "Serverless",
        "Database",
        "API Development",
        "AI",
        "Machine Learning",
        "TensorFlow",
        "TensorFlow js",
        "TensorFlow Lite",
        "Gemini",
        "Gemma",
        "MLKit",
        "Computer Vision",
        "Natural Language Processing",
        "AI Ethics",
        "Generative AI",
        "Web",
        "Progressive Web Apps",
        "Web Performance",
        "Web Security",
        "Angular",
        "Material Design",
        "DevFest",
        "Google I/O Extended",
        "Community Building",
        "Diversity in Tech",
        "Women in Tech",
        "Tech Leadership",
        "Career Development",
        "Open Source",
        "Code Labs",
        "Hackathon",
        "Business",
        "Entrepreneurship",
        "Startup Development",
        "Product Management",
        "Technical Writing",
        "Developer Relations",
        "Google Play",
        "App Monetization",
        "Project Management",
        "AR/VR",
        "Internet of Things",
        "Edge Computing",
        "Blockchain",
        "5G Technologies",
        "Quantum Computing"
      ]
    }
  }))

  return dao.saveCollection(collection)
})
